import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  // Автоматически генерирует меню на основе файловой структуры в docs/
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;