import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Logger } from '@nestjs/common';
import { Job } from 'bullmq';
import { DataSource } from 'typeorm';
import { Auction, AuctionStatus } from '../../auctions/entities/auction.entity';
import { AutoBid } from '../../auctions/entities/autobid.entity';
import { EnglishAuctionConfig } from '../../auctions/entities/english-config.entity';
import { Bid } from '../entities/bid.entity';

@Processor('autobid-tasks')
export class AutobidQueueWorker extends WorkerHost {
  private readonly logger = new Logger(AutobidQueueWorker.name);

  constructor(private readonly dataSource: DataSource) {
    super();
  }

  async process(job: Job<{ auctionId: string }>): Promise<any> {
    if (job.name !== 'check-autobids') return;

    const { auctionId } = job.data;
    const queryRunner = this.dataSource.createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();

    try {
      // Блокируем лот, защищая битва роботов от параллельных живых ставок
      const auction = await queryRunner.manager.findOne(Auction, {
        where: { id: auctionId },
        lock: { mode: 'pessimistic_write' },
      });

      if (!auction || auction.status !== AuctionStatus.ACTIVE) {
        await queryRunner.rollbackTransaction();
        return;
      }

      const config = await queryRunner.manager.findOne(EnglishAuctionConfig, { where: { auction: auction } });
      if (!config) throw new Error('Конфигурация шага цены не найдена.');

      // 1. Вытаскиваем ТОП-2 самых высоких автобида по этому лоту
      const topAutoBids = await queryRunner.manager.find(AutoBid, {
        where: { auction: { id: auctionId } },
        order: { maxAmount: 'DESC' },
        take: 2,
      });

      if (topAutoBids.length === 0) {
        await queryRunner.rollbackTransaction();
        return; // Роботов на лоте нет, ничего делать не нужно
      }

      const currentPrice = Number(auction.currentPrice);
      const minStep = Number(config.minStep);
      
      const leader = topAutoBids[0]; // Самый большой лимит
      const competitor = topAutoBids[1]; // Второй по величине лимит (может отсутствовать)

      let newPrice = currentPrice;
      let targetUser = leader.user;

      if (competitor) {
        // Сценарий А: Конкуренция двух роботов
        const maxLeader = Number(leader.maxAmount);
        const maxCompetitor = Number(competitor.maxAmount);

        if (maxLeader === maxCompetitor) {
          // Если лимиты равны, побеждает тот, кто поставил робота РАНЬШЕ, но цена взлетает до их максимума
          newPrice = maxLeader;
          targetUser = leader.createdAt < competitor.createdAt ? leader.user : competitor.user;
        } else {
          // Если лимиты разные, лидер побеждает конкурента на один шаг выше его максимума
          newPrice = maxCompetitor + minStep;
          if (newPrice > maxLeader) newPrice = maxLeader; // Но не выше потолка лидера
          targetUser = leader.user;
        }
      } else {
        // Сценарий Б: Робот всего один, и он борется с текущей живой ставкой человека
        const maxLeader = Number(leader.maxAmount);
        
        // Получаем последнюю живую ставку в истории лота
        const lastBid = await queryRunner.manager.findOne(Bid, {
          where: { auction: { id: auctionId } },
          order: { createdAt: 'DESC' },
        });

        // Если последняя ставка принадлежит самому владельцу робота — ему не нужно перебивать самого себя
        if (lastBid && lastBid.user.id === leader.user.id) {
          await queryRunner.rollbackTransaction();
          return;
        }

        newPrice = currentPrice + minStep;
        if (newPrice > maxLeader) newPrice = maxLeader;
        targetUser = leader.user;
      }

      // 2. Если математика выявила необходимость поднять цену — пишем ОДНУ финальную ставку от робота
      if (newPrice > currentPrice) {
        const autoGeneratedBid = new Bid();
        autoGeneratedBid.auction = auction;
        autoGeneratedBid.user = targetUser;
        autoGeneratedBid.amount = newPrice;
        autoGeneratedBid.isSubscribedToAutoBid = true;

        await queryRunner.manager.save(Bid, autoGeneratedBid);

        // Обновляем лот
        auction.currentPrice = newPrice;
        
        // Применяем анти-снайпер, если робот сработал на флажке завершения времени
        const now = new Date();
        const msLeft = new Date(auction.endTime).getTime() - now.getTime();
        if (msLeft > 0 && msLeft <= config.antiSniperSeconds * 1000) {
          auction.endTime = new Date(now.getTime() + config.antiSniperSeconds * 1000);
        }

        await queryRunner.manager.save(Auction, auction);
        this.logger.log(`[Autobid] Робот пересчитал цену лота ${auctionId} до ${newPrice} руб. Победитель: ${targetUser.username}`);
      }

      await queryRunner.commitTransaction();
      
      // TODO: Вызов веб-сокета для мгновенного обновления PrimeVue интерфейсов
    } catch (err) {
      await queryRunner.rollbackTransaction();
      this.logger.error(`Ошибка в воркере автобидов: ${err.message}`);
    } finally {
      await queryRunner.release();
    }
  }
}
