import type { ScalarVariableRegistration } from '../scalar-config/bff-scalar-variables.registry';

/** Chat-owned scalar keys — docs/05-microservices/PLATFORM-REGISTRY.md */
export const CHAT_SCALAR_REGISTRY: ScalarVariableRegistration[] = [
  {
    key: 'chat.spawn.copyHistoryMax',
    type: 'number',
    default: 100,
    service: 'chat',
    description: 'Глобальный max N сообщений при копировании истории spawn.',
  },
  {
    key: 'chat.message.editWindowMinutes',
    type: 'number',
    default: 15,
    service: 'chat',
    description: 'Окно правки своего сообщения (мин). 0 — нельзя, -1 — всегда.',
  },
  {
    key: 'chat.message.deleteOwnWindowMinutes',
    type: 'number',
    default: 60,
    service: 'chat',
    description: 'Окно удаления своего сообщения (мин).',
  },
  {
    key: 'chat.message.lengthHardMax',
    type: 'number',
    default: 10000,
    service: 'chat',
    description: 'Абсолютный max длины сообщения (символы).',
  },
  {
    key: 'chat.message.pageSize',
    type: 'number',
    default: 50,
    service: 'chat',
    description: 'Размер страницы истории сообщений (подгрузка вверх). Hard max 100.',
  },
  {
    key: 'chat.markdown.sanitizeLevel',
    type: 'enum',
    default: 'strict',
    service: 'chat',
    description: 'strict | documentation',
  },
  {
    key: 'chat.moderation.bannedWordsList',
    type: 'string[]',
    default: [],
    service: 'chat',
    description: 'Список запрещённых слов.',
  },
  {
    key: 'chat.history.retentionDays',
    type: 'number',
    default: 0,
    service: 'chat',
    description: 'Авто-purge истории (дней). 0 = выкл.',
  },
  {
    key: 'chat.unread.markReadOnOpen',
    type: 'boolean',
    default: true,
    service: 'chat',
    description: 'Отмечать прочитанным при открытии чата.',
  },
  {
    key: 'chat.realtime.typingTtlSeconds',
    type: 'number',
    default: 5,
    service: 'chat',
    description: 'TTL typing indicator (сек).',
  },
  {
    key: 'chat.media.presignTtlSeconds',
    type: 'number',
    default: 900,
    service: 'chat',
    description: 'TTL presign вложений (сек).',
  },
  {
    key: 'chat.topic.authorJoinOnPublish',
    type: 'boolean',
    default: true,
    service: 'chat',
    description: 'Автор темы → TOPIC-room при publish.',
  },
  {
    key: 'chat.topic.joinOnComment',
    type: 'boolean',
    default: true,
    service: 'chat',
    description: 'Join TOPIC при первом комментарии.',
  },
  {
    key: 'chat.dm.selfAutoCreate',
    type: 'boolean',
    default: true,
    service: 'chat',
    description: 'Автосоздание self-DM (заметки).',
  },
  {
    key: 'chat.list.defaultFilter',
    type: 'enum',
    default: 'ALL',
    service: 'chat',
    description: 'ALL | DIRECT | GROUP | TOPIC',
  },
  {
    key: 'chat.group.leaveKeepsHistory',
    type: 'boolean',
    default: true,
    service: 'chat',
    description: 'История для оставшихся после leave.',
  },
];
